# Generated by Django 5.2.7 on 2025-11-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Asistente', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='asistente/')),
            ],
        ),
    ]
