# Generated by Django 5.2.7 on 2026-01-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
