# Generated by Django 5.2.7 on 2026-08-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_corregir_is_user_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteconfig',
            name='color_encabezado',
            field=models.CharField(default='#a855f7', max_length=20),
        ),
        migrations.AddField(
            model_name='asistenteconfig',
            name='imagen_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='fondos/'),
        ),
    ]
